name: 'Terraform'

on:
  pull_request:

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    environment: production

    # Use the Bash shell regardless whether the GitHub Actions runner is ubuntu-latest, macos-latest, or windows-latest
    defaults:
      run:
        shell: bash
        #working-directory: terraform

    steps:
    # Checkout the repository to the GitHub Actions runner
    - name: Checkout
      uses: actions/checkout@v2
      if: github.event_name == 'pull_request'
      with:
        fetch-depth: 0
        ref: ${{ github.event.pull_request.head.ref }}

    # Install the latest version of Terraform CLI and configure the Terraform CLI configuration file with a Terraform Cloud user API token
    - name: Setup Terraform
      uses: hashicorp/setup-terraform@v1

    # Initialize a new or existing Terraform working directory by creating initial files, loading any remote state, downloading modules, etc.
    - name: Terraform Init
      id: init
      run: terraform init

    # Checks that all Terraform configuration files validate
    - name: Terraform Validate
      id: validate
      run: terraform validate -no-color
      continue-on-error: true

    # Checks that all Terraform configuration files adhere to a canonical format
    - name: Terraform Format
      id: fmt
      #run: terraform fmt -check
      run: terraform fmt 
      continue-on-error: true

    - uses: actions/github-script@0.9.0
      #if: github.event_name == 'pull_request'
      env:
        PLAN: "terraform\n${{ steps.plan.outputs.stdout }}"
      with:
        github-token: ${{ secrets.GITHUB_TOKEN }}
        script: |
          const output = `#### Terraform Format and Style 🖌\`${{ steps.fmt.outcome }}\`
          #### Terraform Initialization ⚙️\`${{ steps.init.outcome }}\`
          #### Terraform Validation 🤖\`${{ steps.validate.outputs.stdout }}\`
          *Pusher: @${{ github.actor }}, Action: \`${{ github.event_name }}\`, Working Directory: \`${{ env.tf_actions_working_dir }}\`, Workflow: \`${{ github.workflow }}\`*`;
        
          github.issues.createComment({
            issue_number: context.issue.number,
            owner: context.repo.owner,
            repo: context.repo.repo,
            body: output
          })
        
#    - name: Github push
#      id: github-push
#      #if: steps.fmt.outputs.modified == 'true'
#      continue-on-error: true
#      run: |
#        echo "The event.name = ${{ steps.fmt.outputs.stdout }}"
#        echo "The modified = ${{ steps.fmt.outputs.modified }}"
#        echo "The stdout = ${{ steps.fmt.outputs.stdout }}"
#        echo "The conclusion = ${{ steps.fmt.conclusion }}"
#        echo "The outcome = ${{ steps.fmt.outcome }}"
#        git config --global user.name 'Github auto formatter'
#        git config --global user.email 'autoformat@users.noreply.github.com'
#        git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}
#        git commit -am "Terraform formatting"
#        git push origin
#
    - name: git-auto-commit
      uses: stefanzweifel/git-auto-commit-action@v4
      with:
        # Optional, but recommended
        # Defaults to "Apply automatic changes"
        commit_message: Automated Change
        # Optional branch name where commit should be pushed to.
        # Defaults to the current branch.
        #branch: feature-123
        # Optional. Used by `git-commit`.
        # See https://git-scm.com/docs/git-commit#_options
        commit_options: '--no-verify --signoff'
        # Optional glob pattern of files which should be added to the commit
        # Defaults to all (.)
        # See the `pathspec`-documentation for git
        # - https://git-scm.com/docs/git-add#Documentation/git-add.txt-ltpathspecgt82308203
        # - https://git-scm.com/docs/gitglossary#Documentation/gitglossary.txt-aiddefpathspecapathspec
        file_pattern: *.tf infrastructure/*.tf
        # Optional local file path to the repository
        # Defaults to the root of the repository
        repository: .
        # Optional commit user and author settings
        commit_user_name: My GitHub Actions Bot # defaults to "GitHub Actions"
        commit_user_email: my-github-actions-bot@chegwin.org # defaults to "actions@github.com"
        commit_author: Author <actions@github.com> # defaults to author of the commit that triggered the run
        # Optional tag message 
        # Action will create and push a new tag to the remote repository and the defined branch
        # tagging_message: 'v1.0.0'
        # Optional. Used by `git-status`
        # See https://git-scm.com/docs/git-status#_options
        # status_options: '--untracked-files=no'
        # Optional. Used by `git-add`
        # See https://git-scm.com/docs/git-add#_options
        # add_options: '-u'
        # Optional. Used by `git-push`
        # See https://git-scm.com/docs/git-push#_options
        # push_options: '--force'
        # Optional. Disable dirty check and always try to create a commit and push
        skip_dirty_check: true    
    
        # Optional. Skip internal call to `git fetch`
        skip_fetch: true    
    
       # Optional. Prevents the shell from expanding filenames. 
       # Details: https://www.gnu.org/software/bash/manual/html_node/Filename-Expansion.html
       #disable_globbing: true

